### ISSUE TITLE
Encode migration schema to base64 in export & import schema to escape invalid SQL query

### ISSUE THREAD

**Issue by rrmdn** [feedloop/qore-sdk#56]

**Comment by hubbusysyuhada** [comment]
After trial and error, I found out that the error occurs when importing schema that includes action javascript is mainly because of the single quote `(')` in `migration.schema`, not the `migration.up` query. So I dont think encode the schema, up, and down migration to base64 when exporting schema would fix the problem as we need to decode it to string again when importing schema.

What I could proposed and works well (on my local) is to replace every single quote `(')` in schema (that already parsed into string) into a double single quote`('')` like what I've done for query up and down below 
https://github.com/feedloop/qore-sdk/blob/89787efc362f911da25ae564bdeea0cd89414f72/packages/cli/src/commands/import-schema.ts#L83

the reason why I replace every single quote to a double single quote referred [here](https://www.postgresql.org/docs/current/app-psql.html)

<img width="1315" alt="Screen Shot 2022-06-15 at 15 16 08" src="https://user-images.githubusercontent.com/76815481/173777894-72ea90d3-1313-40d7-b81d-aae7c243f8ea.png">
